name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      
#       FRONTEND
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - run: npm install
      working-directory: './frontend'
    - run: npm run build --if-present
      working-directory: './frontend'
    - run: npm test
      working-directory: './frontend'
      
      #     BACKEND
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: API/package-lock.json
    - run: npm install
      working-directory: './backend'
    - run: npm run build --if-present
      working-directory: './backend'
    - run: npm test
      working-directory: './backend'
